### ISSUE TITLE
Add tourism in Maharashtra

### ISSUE THREAD

**Issue by rudrakshkarpe** [harshvardhansb/TourGuide#108]
Maharashtra comes with great history and tourist places visited by lacks of tourists across the globe. I'd like to add them to TouristGuide.
Please let me know your opinions on this issue :)

**Comment by harshvardhansb** [comment]
yes, you can add places as an image card

**Comment by rudrakshkarpe** [comment]
> yes, you can add places as an image card

Thank I'll start working on it ASAP
