### ISSUE TITLE
Add a cool slider to Website

### ISSUE THREAD

**Issue by Saikatssd** [harshvardhansb/TourGuide#113]
![ripple-loading-effect-image-slider](https://user-images.githubusercontent.com/92164254/197546143-f8c359ae-68b0-4756-92fa-0ff0c2949be2.gif)

**Comment by Saikatssd** [comment]
@harshvardhansb Please assign me to work on this issue.

**Comment by harshvardhansb** [comment]
can u do it little bigger and more toward  center of the screen

**Comment by Saikatssd** [comment]
ok
