### ISSUE TITLE
Add an Image slider

### ISSUE THREAD

**Issue by harshvardhansb** [harshvardhansb/TourGuide#14]
An image slider is already present on the webpage u can modify that or could create a new from scratch ......
Plz try to create a minimal and elegant looking slider with smooth effects....

**Comment by Divyanshi2408** [comment]
@harshvardhansb could you please assign me this

**Comment by harshvardhansb** [comment]
plz send the ss for review before pr

**Comment by Divyanshi2408** [comment]
![slide](https://user-images.githubusercontent.com/85859444/196163370-2f8f7804-cb76-49f9-b14b-59ef8061a2fc.PNG)

please review it

**Comment by harshvardhansb** [comment]
is the overflow intentional?
u can pr if it is ..or hide it and then pr

**Comment by Divyanshi2408** [comment]
I have to create a new folder for this?

**Comment by harshvardhansb** [comment]
u can do if u want or u can just merge it with old index html file ....just keep in check that it's working fine with all existing code....
then u can pr

**Comment by harshvardhansb** [comment]
hey u added the image slider in an folder ...plz integrated it into pre existing index file....and remove the old one.....
otherwise there is no sense of ur slider being in an independent folder...

**Comment by Divyanshi2408** [comment]
okay
