### ISSUE TITLE
The position of image slider should be centered.

### ISSUE THREAD

**Issue by Sachin4219** [harshvardhansb/TourGuide#142]
Another thing when i was added my image card code, the image cards at the bottom don't change is that supposed to happen or is it an error ?

**Comment by harshvardhansb** [comment]
yes

**Comment by harshvardhansb** [comment]
yes, there's an error because some of the last few contributors didn't used proper format while contributing and messed up the some div's...........
you want to correct it I can assign it to u

**Comment by harshvardhansb** [comment]
Anyone interested for this issue can comment here

**Comment by harshvardhansb** [comment]
remove transition bug and make it little bigger

**Comment by Sachin4219** [comment]
I changed the position of svgs and enlarged them. is there any other bug ?

**Comment by harshvardhansb** [comment]
I think it's good for now . if u want add anything from ur side u can create a new issue
