### ISSUE TITLE
Hacksquad.dev team invite 

### ISSUE THREAD

**Issue by horizenightV1** [harshvardhansb/TourGuide#151]
Hey, can you invite me to your hack squad as I have been planning to contribute and this is my alternate id . I am planning in doing 10-12 contributions and if we can do it together we would be able to get into top 60 squad . 

Real ID : [horizenight](https://github.com/horizenight)

**Comment by harshvardhansb** [comment]
how many pr u have till now?

**Comment by harshvardhansb** [comment]
send me ur email...i'll send u the invite link

**Comment by horizenight** [comment]
I have completed 6 prs 2 pending on the main I'd and 

For hacksquad they only consider pr that you do after joining a squad 
I will be using this I'd for making contributions

**Comment by harshvardhansb** [comment]
i don't have that much pr. 
you can team up with someone else
