### ISSUE TITLE
Scroll bar bg. color

### ISSUE THREAD

**Issue by harshvardhansb** [harshvardhansb/TourGuide#159]
Scroll bar's background color should change with change in theme  . and should also have same color as other page .
also try to add same js to make it smooth transition while changing with theme button .
Note: plz send a short video for review before pr

**Comment by Ishikasaraf20** [comment]
hey @harshvardhansb can you assign this issue to me i can work on it

**Comment by khanhtranngoccva** [comment]
I would like to work on this as well!
