### ISSUE TITLE
Bug : One card(Nalanda) background not visible

### ISSUE THREAD

**Issue by MohitNamdev22** [harshvardhansb/TourGuide#161]
![image](https://user-images.githubusercontent.com/89779447/198696834-ff38232e-6243-4103-b82c-0f74421fc4e5.png)

**Comment by harshvardhansb** [comment]
You can add correct image and it source of its image card ....
comment if u want to get assigned to do it

**Comment by richav193** [comment]
please assign this to me

**Comment by MohitNamdev22** [comment]
> You can add correct image and it source of its image card ....
> 
> comment if u want to get assigned to do it

Yes please assign it to me
