### ISSUE TITLE
Modify the social icons in the footer

### ISSUE THREAD

**Issue by zugzwang03** [harshvardhansb/TourGuide#165]
The social icons in the footer do show scaling effect on hovering, but I wanted to add some color changes on them too. Like the Facebook icon can take up the blue color on hovering, and Gmail icon red, it will look attractive, and make it easier to catch up the attention of the viewers.

![footer](https://user-images.githubusercontent.com/95460021/198814189-effe1a2c-89c9-40f4-b040-63b5d67949cd.png)

**Comment by harshvardhansb** [comment]
also add the links to them
tw : https://twitter.com/harsh_vsb
fb : https://www.facebook.com/harshvardhansb
insta : https://www.instagram.com/harshvardhansb/
email : mailto:harsh0vardhan0@gmail.com

...
also github and linkdin ..........
https://github.com/harshvardhansb
https://www.linkedin.com/in/harshvardhansb/
