### ISSUE TITLE
Email Icon link is broken at Footer

### ISSUE THREAD

**Issue by PrakashGatiyala** [harshvardhansb/TourGuide#172]
![image](https://user-images.githubusercontent.com/34413515/198842306-82143684-b40b-4195-8bb4-3050ed7c1a04.png)

When I clicked on Email icon link, It is redirected to a broken link: 
![image](https://user-images.githubusercontent.com/34413515/198842374-b7c8f45a-2a18-4c4a-84a6-374d41038ed2.png)

Ideally, It should Open the Email App if users click on it.  
I want to fix this issue. 
Hi @harshvardhansb  I want to work on this. Can you assign it to me.

**Comment by harshvardhansb** [comment]
email : harsh0vardhan0@gmail.com

**Comment by PrakashGatiyala** [comment]
> email : [harsh0vardhan0@gmail.com](mailto:harsh0vardhan0@gmail.com)

Hi @harshvardhansb PR link: https://github.com/harshvardhansb/TourGuide/pull/173
Please review it and merge it.
