### ISSUE TITLE
On mouse hover over social media Icon, It should show App Title.

### ISSUE THREAD

**Issue by PrakashGatiyala** [harshvardhansb/TourGuide#174]
![image](https://user-images.githubusercontent.com/34413515/198843148-f7e001ec-7ea1-4f47-88a6-d288198d5245.png)

I have done the mouse-hover over social media Icon at footer. It's not displaying the Social_Media_App Name. 

Example: If user mouse-hover over Instagram, it should display Instagram. 

I want to add title property in anchor tag to fix this. 
For example: 
`<a href="https://www.instagram.com/harshvardhansb/" target="_blank" title="Instagram"> <i
                  class="social-icon fa-brands fa-instagram"></i></a>`
Hi @harshvardhansb I want to work on this issue. Can you assign it to me?

**Comment by harshvardhansb** [comment]
it's simple and look better this way ..... you can work on some other issues ...and open a PR faster than other....to merge ur work
