### ISSUE TITLE
Location is missing for some Places

### ISSUE THREAD

**Issue by dellucifer** [harshvardhansb/TourGuide#175]

**Comment by harshvardhansb** [comment]
yup it was implemented later on and was an option for someone to add location if they want with in an image card.
if you want to add locations to the image cards ...i can assign it....
comment if interested

**Comment by dellucifer** [comment]
I have added for some of them, I have forwarded your repo to my friends and told them about the locations, they will do it by tomorrow or day after tomorrow...
