### ISSUE TITLE
Some elements have wrong info and 4 places in a row

### ISSUE THREAD

**Issue by dellucifer** [harshvardhansb/TourGuide#177]

**Comment by harshvardhansb** [comment]
Plz Do correct it if u can .....it would be a great help

**Comment by dellucifer** [comment]
This issue is solved in #178 PR...

**Comment by dellucifer** [comment]
You can close this one...

**Comment by dellucifer** [comment]
> Plz Do correct it if u can .....it would be a great help

I have added another issue #175 for the locations...
This issue was specially for the rows, I fixed them :)
