### ISSUE TITLE
Add navbar in your website

### ISSUE THREAD

**Issue by Swadeshit27** [harshvardhansb/TourGuide#182]

**Comment by Swadeshit27** [comment]
@harshvardhansb please assign me this issue

**Comment by harshvardhansb** [comment]
a  navbar is already there if u can make it better plz do that ...
Note : send a ss for review before pr
....
Also don't make sections on navbar .........only add some animations or anything out of ur own creativity

**Comment by Swadeshit27** [comment]
@harshvardhansb  There is no navbar this is just header. Can I add Home , search, contact Us section ?

**Comment by harshvardhansb** [comment]
yes u can

**Comment by harshvardhansb** [comment]
also try to add same hamburger menu for the phone
