### ISSUE TITLE
Creating a contact us page 

### ISSUE THREAD

**Issue by Vanshiii203** [harshvardhansb/TourGuide#185]
I would like to create a contact us page

**Comment by harshvardhansb** [comment]
some one already did that he/she got a conflict with the pr....so if they don't open another pr in few hours i will assign it to u

**Comment by Vanshiii203** [comment]
> some one already did that he/she got a conflict with the pr....so if they don't open another pr in few hours i will assign it to u

okay!

**Comment by harshvardhansb** [comment]
sorry the guy added that ...still u can see find any new issue or could enhance the website if u like
