### ISSUE TITLE
Images for both New Delhi cards are not fitted fine.

### ISSUE THREAD

**Issue by nihshesh** [harshvardhansb/TourGuide#19]
![image](https://user-images.githubusercontent.com/61341935/194844049-80a1f9f0-8b48-4bce-bfcd-02f99939d5c6.png)

**Comment by nihshesh** [comment]
Please assign me this issue so I can work on this.

**Comment by harshvardhansb** [comment]
It's already been corrected ...if u want u can work on the banner image slider

**Comment by nihshesh** [comment]
Okay thanks, I will do it.
