### ISSUE TITLE
feat : Center the text of copyright part

### ISSUE THREAD

**Issue by Sahil-K123** [harshvardhansb/TourGuide#207]
**The copyright part in the footer is not positioned center .**

It is slightly alligned to left side. By center this , it would look perfect.

![Screenshot 2023-10-01 002352](https://github.com/harshvardhansb/TourGuide/assets/123640518/a5ca04c3-aeaa-440d-ad5b-5d1dab0478ec)

**Comment by Sahil-K123** [comment]
@harshvardhansb can i work on this feature.

**Comment by harshvardhansb** [comment]
> @harshvardhansb can i work on this feature.

yes You can ,

**Comment by sukhmani1303** [comment]
please assign me this issue

**Comment by bbhupen** [comment]
Hi @harshvardhansb, raised a PR regarding this issue. #210 
Should fix the issue.
Please check it

**Comment by Sahil-K123** [comment]
> > @harshvardhansb can i work on this feature.
> 
> yes You can ,

Raise the PR. Please check this.
