### ISSUE TITLE
Contact US Form

### ISSUE THREAD

**Issue by harshvardhansb** [harshvardhansb/TourGuide#209]
Contact Us form is already present but not working ......
use mail to : harshvardhanhbtu@gmail.com

You can also change the UI but it should function properly ....

**Comment by Typical-techno** [comment]
I Can Try to Fix This Assign Me Please

**Comment by harshvardhansb** [comment]
issue still open

**Comment by Hemanthhari2000** [comment]
Hi, I would like to work on this issue under hacktoberfest. Can you please assign this to me?
