### ISSUE TITLE
bug in the page-number buttons 

### ISSUE THREAD

**Issue by Sypher0Dronzer** [harshvardhansb/TourGuide#212]
Sir @harshvardhansb ,
I noticed that on resizing the page for different devices the page-number buttons seem to overflow
and create an unnecessary scrolling. 
![image](https://github.com/harshvardhansb/TourGuide/assets/83546205/1171de76-4d2e-47e7-955d-f0559cd71b36)

May I be assigned this issue. Thank you.

**Comment by harshvardhansb** [comment]
Sure
