### ISSUE TITLE
Image Slider 

### ISSUE THREAD

**Issue by harshvardhansb** [harshvardhansb/TourGuide#216]
Replace the current image slider with something better and it should be responsive too.
Don't change the text and image*.

* You can change images iff you get a better one in place of them

**Comment by amitdhiman5086** [comment]
means new animation or something else

**Comment by Typical-techno** [comment]
I can do this please assign me.

**Comment by harshvardhansb** [comment]
you

> means new animation or something else

YOU can change the  Slider completely as per your wish share the SS too before PR

**Comment by Typical-techno** [comment]
Sir Where i have to send the SS or the video Recording of the Slider

**Comment by harshvardhansb** [comment]
here only

**Comment by Typical-techno** [comment]
![image](https://github.com/harshvardhansb/TourGuide/assets/84324154/900310dd-934d-4d38-8834-1cb9843b06e5)
![image](https://github.com/harshvardhansb/TourGuide/assets/84324154/e4d78efb-b5ee-417f-b445-1bee1b650a51)

**Comment by harshvardhansb** [comment]
you can do better for text .... like instead of white bg use some transparent blur-bg or something .......

**Comment by Typical-techno** [comment]
![image](https://github.com/harshvardhansb/TourGuide/assets/84324154/4b639239-40b5-4c87-824a-321f0231eff2)
![image](https://github.com/harshvardhansb/TourGuide/assets/84324154/ce7f31b8-e419-4c9c-a55c-2e79091ddb4e)

I Have Changed the Design As per Requirement And Also Added the Hover Effect as show in 2nd Pic.
Anything Else i Can Do?

**Comment by harshvardhansb** [comment]
remove the hover effect , rest ok

**Comment by Typical-techno** [comment]
I removed the hover Effect👍
