### ISSUE TITLE
Image slider

### ISSUE THREAD

**Issue by harshvardhansb** [harshvardhansb/TourGuide#221]
add a new image slider for mobile/tablet or make the already existing one responsive

**Comment by HKABIG** [comment]
I would like to work on this 
can you please this  assign this to me

**Comment by harshvardhansb** [comment]
plz show the SS before PR

**Comment by HKABIG** [comment]
![Screenshot 2023-10-02 211025](https://github.com/harshvardhansb/TourGuide/assets/98868227/c09b5b4b-6d61-4beb-af58-b854f5aa4a38)

@harshvardhansb please check this out If OK I will make a PR

**Comment by harshvardhansb** [comment]
the images ain't visible ?

**Comment by HKABIG** [comment]
It's getting distorted somehow

**Comment by harshvardhansb** [comment]
instead of making it responsive you can hide it after some set width and implement your own different mobile friendly image slider .
