### ISSUE TITLE
Buttons : Go to Top & Theme Changer

### ISSUE THREAD

**Issue by harshvardhansb** [harshvardhansb/TourGuide#226]
1> Remove the go to top button in mobile view .
2> Set the theme changing button on top bar (for both mobile & desktop )

note : you can change the UI of it if you want

**Comment by Hemanthhari2000** [comment]
Hi @harshvardhansb, 
I would like to work on this issue. Can you please assign it to me?

**Comment by vd89** [comment]
Hi @harshvardhansb 
- would like to work on the issue. can you assign to me
