### ISSUE TITLE
Add Smooth Scroll Functionality to "Back to Top" Button

### ISSUE THREAD

**Issue by kritikashrmaa** [harshvardhansb/TourGuide#244]
Objective:
The purpose of this issue is to enhance the user experience on our project by implementing a smooth scroll functionality for the "Back to Top" button. Currently, clicking the button instantly takes users to the top of the page, which can be jarring. Adding smooth scrolling will create a more polished and user-friendly experience.
Tasks:
Implementation: Implement smooth scrolling behavior when the "Back to Top" button is clicked. This should provide a visually pleasing transition to the top of the page.
Button Visibility: Ensure that the button is visible when the user scrolls down the page and is hidden when they are at the top.

**Comment by SumitMangrati** [comment]
hello i am new to open source contribution, and i am willing to learn .  I am quite familar with web development and i can add the smooth scrolling feature, could you please assign me this task and guide me .
