### ISSUE TITLE
Unwanted "=======" in the index.html file

### ISSUE THREAD

**Issue by Akash7649** [harshvardhansb/TourGuide#248]
Hey @harshvardhansb I found this in your website :
![image](https://github.com/harshvardhansb/TourGuide/assets/101036630/a07962ce-9ec4-4e6e-a7a3-9d87d42ca7b9)

As you can see at the topmost left corner there is "=======" present which makes the UI look bad so l would like to solve this issue. So please assign me this issue under the tag of Hacktoberfest2023.

**Comment by Himanshuch8055** [comment]
PR is raised check #245
