### ISSUE TITLE
Hamburger menu  & theme change icon

### ISSUE THREAD

**Issue by harshvardhansb** [harshvardhansb/TourGuide#249]
remove the Hamburger menu as it doesn't serve any purpose 
also change theme change icon to something better (you can use pre built components eg. uiverse.io )
https://uiverse.io/rishichawda/fluffy-robin-48

**Comment by insane-22** [comment]
Hey @harshvardhansb! I would like to contribute to your project under hacktoberfest 2023
Kindly assign this issue to me!
Thank you for your consiederation!

**Comment by Arun-Raghav-S** [comment]
Hey @harshvardhansb I am also interested  in working on this issue

**Comment by Arun-Raghav-S** [comment]
@harshvardhansb  Please review my PR #251
