### ISSUE TITLE
Image card named Ganpatipule does not have an image to its background.

### ISSUE THREAD

**Issue by abhishek12201** [harshvardhansb/TourGuide#258]
there is no image in background as you see.
![Screenshot 2023-10-05 200050](https://github.com/harshvardhansb/TourGuide/assets/95902938/ea43bc38-bad3-4a49-a0be-965873832ce6)

**Comment by abhishek12201** [comment]
can you assign this issue to me? I will solve it ASAP. Also add hacktoberfest labels to the issue, please.

**Comment by Himanshuch8055** [comment]
I'm creating a PR regarding this issue check PR/no. #257. this is already solved my me.
