### ISSUE TITLE
Add Search feature : Vanilla JavaScript

### ISSUE THREAD

**Issue by harshvardhansb** [harshvardhansb/TourGuide#262]
Add Search bar and functionality , you can use string matching algo or any technique of your choice 
Make the UI clean and minimal you can use prebuilt components too for the UI . 
Send SS for both mobile & desktop view before PR for review

**Comment by Yash282003** [comment]
@harshvardhansb I would like to work on this issue. Can you please assign it to me?

**Comment by Mohit-0918** [comment]
Hi @harshvardhansb i would like to contribute to this can you please assign it to me

**Comment by Mohit-0918** [comment]
@harshvardhansb Well I have implemented the search technique here is the SS 

![Screenshot from 2023-10-06 19-01-34](https://github.com/harshvardhansb/TourGuide/assets/76563850/cc0742a6-c1d9-406c-aff3-b13942a9ecdf)
![Screenshot from 2023-10-06 19-01-54](https://github.com/harshvardhansb/TourGuide/assets/76563850/97a2c46c-ff78-4358-9f96-e0848b631be6)

**Comment by Mohit-0918** [comment]
@harshvardhansb I have added the search technique do let me know for any changes.
SS are below

![Screenshot from 2023-10-06 19-01-54](https://github.com/harshvardhansb/TourGuide/assets/76563850/fa09b116-822e-4453-a00f-4da2849e9f75)


![Screenshot from 2023-10-06 19-01-34](https://github.com/harshvardhansb/TourGuide/assets/76563850/9b254b86-36f3-4644-a5e2-1516103dd9d9)

**Comment by harshvardhansb** [comment]
howz the search bar ?
you can PR

**Comment by rituraj12797** [comment]
i want to work on this please please assign to me also

**Comment by rituraj12797** [comment]
so we just need to add the search component in the page? as no api is currently linked in the javascript file to link with the search cimponent.
