### ISSUE TITLE
Add some  cards

### ISSUE THREAD

**Issue by harshvardhansb** [harshvardhansb/TourGuide#3]
If u can add some Places to Visit cards plz do 
I won't assign this...
to do that just read README file ...all the details are there

**Comment by nikzayn** [comment]
@harshvardhansb Please assign this to me!

**Comment by harshvardhansb** [comment]
this issue is to get assigned ,you can simply add image card like everyone else with direct PRs

**Comment by nikzayn** [comment]
> 

Sure @harshvardhansb thanks for informing!
