### ISSUE TITLE
add new section.

### ISSUE THREAD

**Issue by Kamal-Rathore** [harshvardhansb/TourGuide#305]
want to add the new section to tour.

Content of beaches and backwater are same.
pls assign this issue.
![Screenshot (318)](https://github.com/harshvardhansb/TourGuide/assets/127128416/5f90bebf-4fd1-4f68-878e-bf039a7102b4)
![Screenshot (302)](https://github.com/harshvardhansb/TourGuide/assets/127128416/237188c5-f01e-4e2e-b595-935f0374077e)

**Comment by Bishwajitpvt** [comment]
hey @harshvardhansb  can you assign this issue to me

**Comment by Bishwajitpvt** [comment]
created PR #307
