### ISSUE TITLE
Create a good looking scroll bar for the web-page

### ISSUE THREAD

**Issue by harshvardhansb** [harshvardhansb/TourGuide#68]

**Comment by heza-ru** [comment]
Hello, I made a sample for this if its fine i would like to send a PR.
![Screenshot 2022-10-15 162106](https://user-images.githubusercontent.com/113707801/195982523-a59051e9-a725-44bf-b1a0-ebf6f0694e92.jpg)

**Comment by harshvardhansb** [comment]
okay send it

**Comment by heza-ru** [comment]
done
