### ISSUE TITLE
Slider text Not visible

### ISSUE THREAD

**Issue by Ayushhgupta39** [harshvardhansb/TourGuide#74]
The information written on the main slider is not visible. I'll enhance by changing the style a bit and make it easy to read.

<img width="237" alt="image" src="https://user-images.githubusercontent.com/96309609/196022519-c959c6b0-2def-451e-a45b-d82fb6e04cf6.png">
<img width="212" alt="image" src="https://user-images.githubusercontent.com/96309609/196022548-ef718a32-4b83-4365-8032-f0e5b9a05ce0.png">

Assign me this and add Hacktoberfest and Hacktoberfest-accepted label.

**Comment by harshvardhansb** [comment]
send the ss for review before pr

**Comment by harshvardhansb** [comment]
try blur when hover effect if u can

**Comment by Ayushhgupta39** [comment]
Okay
Add the labels.
