### ISSUE TITLE
Ambalappuzha Sri Krishna Temple

### ISSUE THREAD

**Issue by ayushisingh73448** [harshvardhansb/TourGuide#81]
Issue no:#4

**Comment by harshvardhansb** [comment]
plz balance the last 2 rows

**Comment by ayushisingh73448** [comment]
Will you please elaborate which last 2 rows you are referring to?

**Comment by harshvardhansb** [comment]
Since every row div has three  Cards in it, but the last two doors contains 4 cards. So can you just change the dev location on the code.........

**Comment by ayushisingh73448** [comment]
I have already done that part by my side. You can check it if there is
still the same problem you can tell me.
