### ISSUE TITLE
Add theme changer

### ISSUE THREAD

**Issue by AnshuPathak-88825** [harshvardhansb/TourGuide#86]
pls assign me this issue

**Comment by harshvardhansb** [comment]
send some ss for review before any pr

**Comment by AnshuPathak-88825** [comment]
ok

**Comment by Vishesh-Vijay** [comment]
please assign me this issue

**Comment by harshvardhansb** [comment]
already assigned 
u can work on some other issue...u can also create any relevant issue by ur own ......

**Comment by AnshuPathak-88825** [comment]
https://user-images.githubusercontent.com/78332454/197038672-91fa1186-c57f-4444-b3d7-6836f99f8e13.mp4
Added theme changer demo video of my work is here

**Comment by AnshuPathak-88825** [comment]
pls merge my pull request

**Comment by harshvardhansb** [comment]
hey is there any way u can put that icon inside a sqaure with some opacity it may look better..........

**Comment by AnshuPathak-88825** [comment]
can i raise issue for that ?

**Comment by harshvardhansb** [comment]
yes you can
