### ISSUE TITLE
Add icon to back to top button and also make it smooth scroll

### ISSUE THREAD

**Issue by AnshuPathak-88825** [harshvardhansb/TourGuide#90]
pls assign me this issue 
![image](https://user-images.githubusercontent.com/78332454/197137555-0fa7ea84-d148-4efd-a58f-681f013952ec.png)

**Comment by harshvardhansb** [comment]
hey u doing hacksquad ! ...how many team members r there?

**Comment by harshvardhansb** [comment]
okay

**Comment by AnshuPathak-88825** [comment]
made pr pls merge it

**Comment by AnshuPathak-88825** [comment]
https://user-images.githubusercontent.com/78332454/197372786-d65525bd-0e53-4c33-9a69-3cdf4c2dd619.mp4

it is working perfectly

**Comment by harshvardhansb** [comment]
plz remove blur effects from theme changer and this button

**Comment by AnshuPathak-88825** [comment]
Removed blur effect @harshvardhansb

**Comment by ABHAY-Y** [comment]
Sir, can you assign this task to me?

**Comment by AnshuPathak-88825** [comment]
@ABHAY-Y this issue already been fixed
